export default {
  name: 'themeSettings',
  title: 'Theme Settings',
  type: 'object',
  fields: [
    {
      name: 'headerIconsColor',
      title: 'Header Icons Color',
      type: 'string',
      initialValue: '#313638',
    },
    {name: 'mainBackground', title: 'Main Background', type: 'string', initialValue: '#525659'},
    {name: 'headerBackground', title: 'Header Background', type: 'string', initialValue: '#571926'},
    {name: 'headerTextColor', title: 'Header Text Color', type: 'string', initialValue: '#FFFFFF'},
    {
      name: 'sidebarBackground',
      title: 'Sidebar Background',
      type: 'string',
      initialValue: '#313638',
    },
    {
      name: 'sidebarSectionTextColor',
      title: 'Sidebar Section Text Color',
      type: 'string',
      initialValue: '#7f2437',
    },
    {
      name: 'sidebarTextColor',
      title: 'Sidebar Text Color',
      type: 'string',
      initialValue: '#e5e5e5',
    },
    {name: 'mainTextColor', title: 'Main Text Color', type: 'string', initialValue: '#000000'},
    {
      name: 'mainSectionBackground',
      title: 'Main SectionBackground',
      type: 'string',
      initialValue: '#FFFFFF',
    },
    {
      name: 'mainSectionDotColor',
      title: 'Main Section Dot Color',
      type: 'string',
      initialValue: '#571926',
    },
    {
      name: 'mainSectionLineColor',
      title: 'Main Section Line Color',
      type: 'string',
      initialValue: '#571926',
    },
    {
      name: 'mainSectionTextColor',
      title: 'Main Section Text Color',
      type: 'string',
      initialValue: '#571926',
    },
    {
      name: 'mainSectionPrimaryTextColor',
      title: 'Main Section Primary Text Color',
      type: 'string',
      initialValue: '#571926',
    },
    {
      name: 'mainSectionSecondaryTextColor',
      title: 'Main Section Secondary Text Color',
      type: 'string',
      initialValue: '#232323',
    },
    {name: 'footerTextColor', title: 'Footer Text Color', type: 'string', initialValue: '#313638'},
    {
      name: 'footerIconsColor',
      title: 'Footer Icons Color',
      type: 'string',
      initialValue: '#313638',
    },
    {
      name: 'footerLinkColor',
      title: 'Footer Link Color',
      type: 'string',
      initialValue: '#571926',
    },
  ],
}
