export default {
  name: 'themeSettings',
  title: 'Theme Settings',
  type: 'object',
  fields: [
    {
      name: 'headerIconsColor',
      title: 'Header Icons Color',
      type: 'string',
      initialValue: '#000000',
    },
    {name: 'mainBackground', title: 'Main Background', type: 'string', initialValue: '#525659'},
    {name: 'headerBackground', title: 'Header Background', type: 'string', initialValue: '#F8F9FA'},
    {name: 'headerTextColor', title: 'Header Text Color', type: 'string', initialValue: '#000000'},
    {
      name: 'sidebarBackground',
      title: 'Sidebar Background',
      type: 'string',
      initialValue: '#F1F1F1',
    },
    {
      name: 'sidebarSectionTextColor',
      title: 'Sidebar Section Text Color',
      type: 'string',
      initialValue: '#333333',
    },
    {
      name: 'sidebarTextColor',
      title: 'Sidebar Text Color',
      type: 'string',
      initialValue: '#FFFFFF',
    },
    {name: 'mainTextColor', title: 'Main Text Color', type: 'string', initialValue: '#333333'},
    {
      name: 'mainSectionBackground',
      title: 'Main SectionBackground',
      type: 'string',
      initialValue: '#7F2437',
    },
    {
      name: 'mainSectionDotColor',
      title: 'Main Section Dot Color',
      type: 'string',
      initialValue: '#7F2437',
    },
    {
      name: 'mainSectionLineColor',
      title: 'Main Section Line Color',
      type: 'string',
      initialValue: '#CCCCCC',
    },
    {
      name: 'mainSectionTextColor',
      title: 'Main Section Text Color',
      type: 'string',
      initialValue: '#FFFFFF',
    },
    {
      name: 'mainSectionPrimaryTextColor',
      title: 'Main Section Primary Text Color',
      type: 'string',
      initialValue: '#007BFF',
    },
    {
      name: 'mainSectionSecondaryTextColor',
      title: 'Main Section Secondary Text Color',
      type: 'string',
      initialValue: '#6C757D',
    },
    {name: 'footerTextColor', title: 'Footer Text Color', type: 'string', initialValue: '#FFFFFF'},
    {
      name: 'footerIconsColor',
      title: 'Footer Icons Color',
      type: 'string',
      initialValue: '#FFFFFF',
    },
    {
      name: 'footerLinkColor',
      title: 'Footer Link Color',
      type: 'string',
      initialValue: '#FFFFFF',
    },
  ],
}
